name: composite

on:
  workflow_dispatch:

jobs:
  composite:
    name: Composite
    runs-on: ubuntu-latest
    steps:
      - name: checkout-main-repo
        uses: actions/checkout@v5

      - name: checkout-sub-repo
        uses: actions/checkout@v4
        with:
          repository: vrossiciandt/caller
          path: subrepo

      - name: get-latest-tag
        uses: vrossiciandt/composite/report@main